import type { Metadata } from 'next'
import { Nunito,Playfair_Display,Poppins } from 'next/font/google'
import './globals.css'

const nunito = Nunito({ subsets: ['latin'],
weight:["200","300","400","500","600","700","800","900"],
variable:'--font-nunito' })

const play_fair = Playfair_Display({ subsets: ['latin'],
weight:["400","500","600","700","800","900"],
variable:'--font-play_fair' })

const poppins = Poppins({ subsets: ['latin'],
weight:["400","500","600","700","800","900"],
variable:'--font-play_fair' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${nunito.variable}`}>{children}</body>
    </html>
  )
}
